export const EXPERIENCE_ENTRIES = [
  {
    range: { start: '2026', end: null },
    role: 'Software Engineer intern',
    org: 'Seco Tools',
    location: 'Erkrath, Germany',
    type: 'Internship',
    blurb: 'Building VR factory tour for a cutting tools manufacturing company. Mixing 360° video with 3D assets, spatial audio, interactive hotspots.',
    tags: ['VR', 'Unity', 'C#', 'Meta Quest', 'XR Interaction Toolkit'],
  },
  {
    range: { start: '2023', end: '2024' },
    role: 'AI Engineer',
    org: 'Sentience',
    location: 'Seoul, South Korea',
    type: 'Full-time',
    blurb: 'Created AI opponent using deep reinforcement learning for South Pole Bebop PvPvE game. Built the training pipeline and evaluation harness, ran experiments on model architectures and reward shaping. Started as an intern.',
    tags: ['Python', 'PyTorch', 'Ray RLlib', 'Reinforcement Learning', 'Game AI', 'Gymnasium', 'Unity', 'Go'],
  },
  {
    range: { start: '2023', end: '2023' },
    role: 'Research Intern, Software Engineering',
    org: 'COINSE Lab, KAIST',
    location: 'Daejeon, South Korea',
    type: 'Graduation thesis internship',
    blurb: 'Worked on my graduation thesis.',
    publication: {
      venue: 'IEEE Transactions on Software Engineering',
      title: 'Evaluating Diverse Large Language Models for Automatic and General Bug Reproduction',
      href: 'https://dl.acm.org/doi/10.1109/TSE.2024.3450837',
    },
    tags: ['Python', 'Hugging Face', 'OpenAI API', 'Code LLMs', 'Software Engineering'],
  },
  {
    range: { start: '2021', end: '2022' },
    role: 'Research Intern, HCI',
    org: 'Make Lab, KAIST',
    location: 'Daejeon, South Korea',
    type: 'Internship',
    blurb: 'Explored visuo-haptic illusions in VR.',
    publication: {
      venue: 'IASDR 2023',
      title: 'Designing visuo-haptic illusions for Virtual Reality applications using floor-based shape-changing displays',
      href: 'https://dl.designresearchsociety.org/iasdr/iasdr2023/fullpapers/164/',
    },
    tags: ['VR', 'HCI', 'Unity', 'C#'],
  },
];
