export const EXPERIENCE_ENTRIES = [
  {
    range: { start: '2026', end: null },
    role: 'AI Engineer',
    org: 'KOZ AI',
    type: 'Full-time',
    blurb: 'Demand forecasting for QSR kitchens — cutting food waste and speeding up prep.',
    tags: ['Python', 'Time Series', 'Forecasting', 'Clustering', 'Statistical Modeling'],
  },
  {
    range: { start: '2026', end: '2026' },
    role: 'Software Engineer intern',
    org: 'Seco Tools',
    location: 'Erkrath, Germany',
    type: 'Internship',
    blurb: 'Built VR factory tours and immersive training experiences for industrial clients.',
    tags: ['VR', 'Unity', 'C#', 'Meta Quest', 'XR Interaction Toolkit'],
  },
  {
    range: { start: '2023', end: '2024' },
    role: 'AI Engineer',
    org: 'Sentience',
    location: 'Seoul, South Korea',
    type: 'Full-time',
    blurb: 'Built reinforcement-learning game AI, from training pipeline to evaluation. Started as an intern.',
    tags: ['Python', 'PyTorch', 'Ray RLlib', 'Reinforcement Learning', 'Game AI', 'Gymnasium', 'Unity', 'Go'],
  },
  {
    range: { start: '2023', end: '2023' },
    role: 'Research Intern, Software Engineering',
    org: 'COINSE Lab, KAIST',
    location: 'Daejeon, South Korea',
    type: 'Graduation thesis internship',
    blurb: 'Worked on my graduation thesis.',
    tags: ['Python', 'Hugging Face', 'OpenAI API', 'Code LLMs', 'Software Engineering'],
  },
  {
    range: { start: '2021', end: '2022' },
    role: 'Research Intern, HCI',
    org: 'Make Lab, KAIST',
    location: 'Daejeon, South Korea',
    type: 'Internship',
    blurb: 'Explored visuo-haptic illusions in VR.',
    tags: ['VR', 'HCI', 'Unity', 'C#'],
  },
];
